name: emeeting_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_svg: 1.0.3
  get_storage: ^2.0.3
  font_awesome_flutter: ^9.1.0
  http: ^0.13.5
  intl: 0.17.0
  qr_code_scanner: ^1.0.1
  slide_to_act: ^2.0.1

  firebase_core: ^1.4.0
  firebase_messaging: ^11.2.8
  firebase_analytics: ^8.3.4
  # flutter_local_notifications: ^8.0.0
  flutter_local_notifications: ^9.2.0
  geolocator: 9.0.1
  geocoding: 2.0.5

  rxdart: 0.27.5
  flutter_launcher_icons: ^0.9.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/lotties/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
  uses-material-design: true
